USE [wmsradius3]
GO
CREATE ROLE [ROLE_ZTS_J]
GO
Grant SELECT, VIEW DEFINITION to ROLE_ZTS_J;
GRANT ALTER, EXECUTE, INSERT, UPDATE, DELETE  ON SCHEMA::zts TO ROLE_ZTS_J;
GRANT CREATE TABLE, CREATE PROCEDURE, CREATE FUNCTION, CREATE VIEW TO ROLE_ZTS_J;