USE [wmpoperatorusage]
GO

/****** Object:  Index [INX_INVOICEITEMDETAILS_4UsageFile_SERVICEIDZONEID]    Script Date: 7/19/2016 9:42:04 AM ******/
DROP INDEX [INX_INVOICEITEMDETAILS_4UsageFile_SERVICEIDZONEID] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
GO

/****** Object:  Index [INX_INVOICEITEMDETAILS_4usagefile_INVOICEITEMID_FK]    Script Date: 7/19/2016 9:42:04 AM ******/
DROP INDEX [INX_INVOICEITEMDETAILS_4usagefile_INVOICEITEMID_FK] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
GO

/****** Object:  Index [INX_INVOICEITEMDETAILS_4UsageFile_INVOICEITEMDID_FK]    Script Date: 7/19/2016 9:42:04 AM ******/
DROP INDEX [INX_INVOICEITEMDETAILS_4UsageFile_INVOICEITEMDID_FK] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
GO

/****** Object:  Index [INX_INVOICEITEMDETAILS_4UsageFile_Billing]    Script Date: 7/19/2016 9:42:04 AM ******/
DROP INDEX [INX_INVOICEITEMDETAILS_4UsageFile_Billing] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
GO

/****** Object:  Index [INVOICEITEMDETAILS_4UsageFile_PK]    Script Date: 7/19/2016 9:42:04 AM ******/
ALTER TABLE [dbo].[INVOICEITEMDETAILS_4UsageFile] DROP CONSTRAINT [INVOICEITEMDETAILS_4UsageFile_PK]
GO

/****** Object:  Index [Inx_INVOICEITEMDETAILS_BILLINGSESSIONID_4UsageFile_FK]    Script Date: 7/19/2016 9:42:04 AM ******/
DROP INDEX [Inx_INVOICEITEMDETAILS_BILLINGSESSIONID_4UsageFile_FK] ON [dbo].[INVOICEITEMDETAILS_4UsageFile] WITH ( ONLINE = OFF )
GO

/****** Object:  Index [Inx_INVOICEITEMDETAILS_BILLINGSESSIONID_4UsageFile_FK]    Script Date: 7/19/2016 9:42:04 AM ******/
CREATE CLUSTERED INDEX [Inx_INVOICEITEMDETAILS_BILLINGSESSIONID_4UsageFile_FK] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
(
	[BILLINGSESSIONID_FK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [Invoices]
GO

/****** Object:  Index [INVOICEITEMDETAILS_4UsageFile_PK]    Script Date: 7/19/2016 9:42:04 AM ******/
ALTER TABLE [dbo].[INVOICEITEMDETAILS_4UsageFile] ADD  CONSTRAINT [INVOICEITEMDETAILS_4UsageFile_PK] PRIMARY KEY NONCLUSTERED 
(
	[INVOICEITEMDETAILID] ASC,
	[BILLINGSESSIONID_FK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [Invoices]
GO

/****** Object:  Index [INX_INVOICEITEMDETAILS_4UsageFile_Billing]    Script Date: 7/19/2016 9:42:04 AM ******/
CREATE NONCLUSTERED INDEX [INX_INVOICEITEMDETAILS_4UsageFile_Billing] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
(
	[INVOICEITEMID_FK] ASC,
	[BILLINGSESSIONID_FK] ASC
)
INCLUDE ( 	[PRICEPLANROUNDEDDATA],
	[PRICEPLANROUNDEDDURATION],
	[DISCOUNTED],
	[SERVICECHARGE],
	[TAX],
	[DISCOUNT],
	[TOTALCHARGE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [Invoices]
GO

/****** Object:  Index [INX_INVOICEITEMDETAILS_4UsageFile_INVOICEITEMDID_FK]    Script Date: 7/19/2016 9:42:04 AM ******/
CREATE NONCLUSTERED INDEX [INX_INVOICEITEMDETAILS_4UsageFile_INVOICEITEMDID_FK] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
(
	[INVOICEITEMID_FK] ASC,
	[BILLINGSESSIONID_FK] ASC,
	[INVOICEITEMDETAILID] ASC
)
INCLUDE ( 	[ZONEID_FK],
	[OCTETSIN],
	[OCTETSOUT],
	[TOTALDATA]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [INVOICES]
GO

/****** Object:  Index [INX_INVOICEITEMDETAILS_4usagefile_INVOICEITEMID_FK]    Script Date: 7/19/2016 9:42:04 AM ******/
CREATE NONCLUSTERED INDEX [INX_INVOICEITEMDETAILS_4usagefile_INVOICEITEMID_FK] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
(
	[INVOICEITEMID_FK] ASC,
	[BILLINGSESSIONID_FK] ASC
)
INCLUDE ( 	[OCTETSIN],
	[OCTETSOUT],
	[TOTALDATA],
	[ZONEID_FK]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [Invoices]
GO

/****** Object:  Index [INX_INVOICEITEMDETAILS_4UsageFile_SERVICEIDZONEID]    Script Date: 7/19/2016 9:42:04 AM ******/
CREATE NONCLUSTERED INDEX [INX_INVOICEITEMDETAILS_4UsageFile_SERVICEIDZONEID] ON [dbo].[INVOICEITEMDETAILS_4UsageFile]
(
	[SERVICEID_FK] ASC
)
INCLUDE ( 	[INVOICEITEMID_FK],
	[ZONEID_FK],
	[SERVICECHARGE],
	[DISCOUNT],
	[TOTALCHARGE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [Invoices]
GO


