EXEC sp_depends @objname = N'HumanResources.Employee' 

EXEC sp_MSdependencies N'HumanResources.[Employee]', null, 1053183


SET STATISTICS PROFILE OFF
GO
SET STATISTICS TIME ON
GO
DBCC FREEPROCCACHE
GO
DBCC DROPCLEANBUFFERS
GO
--SET SHOWPLAN_TEXT OFF
--GO

--SET STATISTICS IO OFF
--GO


UPDATE STATISTICS CLIENT

UPDATE STATISTICS CLIENT